name: "Terraform"

on:
  push:
    branches:
      - update-tfc-backend
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
       - name: Terraform Destroy
         id: destroy
         run: terraform destroy -auto-approve
